### ISSUE TITLE
Implement background/async deletes of defunct blobs

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#298]
Defunct blobs are
1. successfully put chunks of PUT operations that eventually failed;
2. data chunks of deleted composite blobs (the deletes of which complete by just deleting the respective metadata chunks).

This will need some thinking through and a write-up before implementation.

**Comment by sriramsub** [comment]
Great. A quick design document on this feature would be useful. Please attach it to this issue.

**Comment by xiahome** [comment]
# Data-Chunk Deletion in NB Router
## Motivation
The current `NonBlocking Router` handles a *composite blob* (a large blob that consists of a number of small *data-chunk blobs*) deletion in such a way that it only marks the *metadata blob* of the composite blob as deleted. The metadata blob consists the blob ids of the data chunk blobs. This approach is based on the fact that the metadata blob is the single pointer possessed by users to the composite blob. Once the metadata blob is marked as deleted, users will not be able to get the composite blob. 

However, the data chunks, which store the actual content, are left in the storage layer without being touched. Once compaction is implemented (the process of removing the blobs that are marked as deleted from hard disk and reclaiming disk space), the data chunks would not be removed from the storage layer, and the space could not be reclaimed. Additionally, they could be get/accessed when their ids are leaked. Therefore, the data chunks need to be deleted together with the deletion of a metadata blob.

## Proposed approaches
A number of approaches have been proposed and discussed with pros and cons.
### Approach 1
1. `DeleteManager` maintains a list of `deleteChunkOperations`. 

2. Through the original request to delete a metadata blob, a list of actual data chunks can be obtained from the metadata blob. After the metadata blob has been successfully deleted, all the data chunks are made into `DeleteOperations` and added to `deleteChunkOperations`. 

3. After polling the delete operations for metadata blobs in `DeleteManager.poll()`, it continues to poll `deleteChunkOperations` and delete all the data chunks. Therefore, chunk deletion happens within the `requestResponseHandler` thread of the corresponding `Operation Controller` (OC). 

This implementation is simple and straightforward. However, delete-chunk operations will be inserted among regular operations (`put/get/delete`) that belong to the same OC, and will possibly introduce extra delay as all of them are processed by the same thread.

A possible solution to this issue could be throttling the number of data chunks to be deleted in one loop of `requestResponseHandler`. Assuming that at some particular time, a number of large blobs needs to be deleted, with each one consisting of 1k data chunks. Within the loop of `requestResponseHandler` thread, we can limit the number of data-chunk deletion by a preset value, which can be determined by performance evaluation. By doing this, we can average out the peak data chunk deletions over a wider time span without impacting the normal operations (`put, get, and delete metadata`).

### Approach 2
A separate thread (called `ChunkRemover`) is running within a `DeleteManager`. The `ChunkRemover` is another `DeleteManager` (extended from `DeleteManager`) that is dedicated to deleting data chunks. This implementation will decouple metadata blob deletion and data-chunk deletion, and the delete operations responding to the original requests will not be impacted by data-chunk deletion. Note that the way a selector works is that it can be polled from only a single thread, this means the `ChunkRemover` thread cannot share the selector of its `DeleteManager`, and needs to have its own selector. Details are as follows.

### Approach 3
Similar to Approach 2, with the major difference being that the `NonBlockingRouter` instead of each DeleteManager owns a ChunkRemover. Again, the `ChunkRemover` will have its own selector dedicated to network-related processing for chunk deletions.

## Discussion
At the time of design there is no estimation on the traffic of data-chunk deletion, and hence we take Approach 1 for a simple start and for avoiding additional threads.

On exception during the runtime of `ChunkRemover`, in both Approach 2 and 3, the `ChunkRemover` thread should try to restart as this exception will not impact the main functionality of a `DeleteManager` or a NB router. Once the `ChunkRemover` thread is restarted, it simply resumes reading and processing the `deleteChunkOperations` list.

On exception of the entire router, there may be pending elements in the `deleteChunkOperations` list, which have not yet gotten a chance to process and will be lost during the crash. We handle this situation at the best effort (i.e., leave these probably very few chunks undeleted, which may cause a small storage leakage), and have them possibly removed by future compaction operation. Compaction design needs to take this into account.

```
Approach 2 key pseudo code

Class DeleteManager {
 List<DeleteOperations> deleteChunkOperations;

 public void poll(List<RequestInfo> requestListToFill) {
   …
   for(DeleteOperation op: deleteOperations) {
     …
     op.poll(requestRegistrationCallback) // chunks will be added to deleteChunkOperations within the call of this method.
     …
 }

  DeleteManager(...) {
    …
    ChunkRemover chunkRemover = new ChunkRemover();
    chunkRemover.start();
  }
}

private class ChunkRemover extends DeleteManager implements Runnable {
  NetworkClient networkClient; 
  ChunkRemover() {
   super(clusterMap, responseHandler, notificationSystem, routerConfig, routerMetrics, operationCompleteCallback, time);
 } //will supply different arguments if needed.
 
 @Override
 public void run() { //this part behaves similarly to the requestResponseHandler thread
   while (isOpen.get()) {
     List<RequestInfo> requestInfoList = pollForRequests();
     List<ResponseInfo> responseInfoList = networkClient.sendAndPoll(requestInfoList);
     onResponse(responseInfoList);
    }
  }
}
```

**Comment by xiahome** [comment]
# Flow of fetching data blobs for composite-blob deletion
To delete a composite blob, a `DeleteManager` first needs to get the content of the metadata blob, which includes the blob ids to the data blobs. However, this process involves several issues:
* A blobId itself does not include the information if the blob is a metadata blob or a simple blob. Even the to-be-deleted blob is a simple blob, the `DeleteManager` has to contact the blob store to get this information;
* The deletion of a composite blob may incur extra round-trip time between the frontend and the blob store due to getting the blob content. However, the caller only needs to wait after the metadata blob is deleted;
* Deletion of a simple blob may unnecessarily get the full content, only for the purpose of determining this is not a metadata blob.

A preliminary study leads to two approaches to data blob deletion.
## Approach 1:
High-levelly, deleting a blobId involves two steps: 1) getting the blob content; and 2) delete the original blob, and delete the data blobs if the original blob is a composite blob. This approach has the pros of requiring no support/modification at the store server. However, it has the drawbacks of one extra RTT and unnecessary fetch of a simple blob. The flow chart of approach 1 is described in Figure 1.
![approach-1](https://cloud.githubusercontent.com/assets/8271368/16402049/34ae6428-3c9e-11e6-8693-974f292cf380.png)
Figure 1. Approach 1 that completes metadata blob deletion in two round trips.

## Approach 2:
This approach requires support from the blob store. When a blob is submitted, the `DeleteManager` just performs a `DeleteOperation` regardless the blob is a metadata blob or a simple blob. When the `DeleteRequest` is received by a blob store, the store needs extra logic to check the type of the blob. If it is a simple blob, the store simply responds a `DeleteResponse` as what it does today. On the other hand, if the blob is a metadata blob, the store will respond a `GetResponse`, which includes the content of the metadata blob. When the `DeleteManager` receives the response, it will also check the type of the response. For both response types, the `DeleteManager` will complete the `DeleteOperation` in the normal flow. In addition, if the response is a `GetResponse`, it will extract the blob content, and generate `DeleteOperations` for each of the data blob. Note that besides the included blob content, a `GetResponse` as an indicator is equivalent to a successful `DeleteResponse`. If there is any error happened during the get operation in the blob store, a `DeleteResponse` will be sent to the router, even the to-be-deleted blob is a metadata blob. The flow chart of approach 2 is described in Figure 2.
![approach-2](https://cloud.githubusercontent.com/assets/8271368/16402050/3b2e22a2-3c9e-11e6-88b8-15bad922664b.png)
Figure 2. Approach 2 that completes metadata blob deletion in a single round trip.

**Comment by pnarayanan** [comment]
I am going to put up a PR for this. It uses the ideas presented here, with some variations (not presenting any design documents as I don't think this warrants any more):

- A special `OperationController` called the `BackgroundDeleter` will be introduced in the router, which is responsible for handling background deletions. For the purpose described in this issue, the `BackgroundDeleter` will delete chunks of a deleted composite blob. Going forward, this can also take care of deleting successfully put chunks of a failed composite blob put operation (which, today, is done in the same `OperationController` that does the puts).
- Deletes will work as it does today, with one simple variation: any blob that is successfully deleted, will be handed over to the `BackgroundDeleter` so that the latter can delete data chunks of that blob (if there are any).
- The `BackgroundDeleter` being a separate `OperationController` will have its own NetworkClient with its own pool (so that this does not interfere with the regular operations).
- The `BackgroundDeleter` will get the blob that was just deleted by the router (by passing in the `Include_All` option). If the fetched blob turns out to be composite, it will deserialize and get the chunk ids and delete the data chunks.
- The `BackgroundDeleter` can later also be throttled if necessary, and the delete operations are best-effort.

**Comment by vgkholla** [comment]
I think an approach 3 - which is that the store takes care of this - is worth exploring and the right solution in terms of correctness and reliability. I know this will mean that the store has to interpret the type of the blob, but looking at #498, it feels more and more like a store based solution is the right solution. There might be other drawbacks but it should be explored (#498 can be merged nevertheless and disabled later if we have a better solution).

**Comment by pnarayanan** [comment]
Yeah the server (perhaps not the store) could deal with this too, but that would involve possibly deserializing during a `Get` which it is not designed to do today, and possibly breaking some abstractions that are in place today (but those abstractions may not be necessary). @asinghai suggested something similar.
This is all done in order to ensure that the delete latency does not suffer. With the current approach, the only real drawback I see is if the store hard deletes or compacts the metadata blob between the time it is deleted and a `Get` is done by the `BackgroundDeleter`. I think the probability of that occurring is pretty low. Other than that, do you see any reason to do this in the server?

**Comment by vgkholla** [comment]
Two main things I suppose. One, the fact that it is "best-effort". Two, the frontend is supposed to be stateless and this looks very close to something that looks like a "state".

Besides, even normal frontend restarts (not even crashes) might cause deletes to get interrupted - which is not a very good guarantee.

**Comment by pnarayanan** [comment]
When we say "stateful" we are always talking about on-disk state. In-memory state is unavoidable and there is really no reason to not keep in-memory state at all. As long as "best-effort" is what we are going for, I think this is a non-issue.

As for whether we can do better than "best-effort", that is a much more involved problem and requires a larger discussion. First of all Ambry is not a transactional system. In general,
- a `Put` operation can complete in a few or all servers and yet fail as far as the user is concerned and no cleanup will be done. If you think about it, there is nothing that can be done here if the frontend fails before returning to the user - unless the frontend keeps disk state.
- a `Delete` operation can succeed in a few servers and fail in others, and the user facing operation might be a failure, and yet the object could be deleted.

There may be more and these cases are in addition to other failures involving machines or disks going down permanently and all that. This problem can only be solved if we introduce some kind of a WAL (Write-Ahead-Logging) within the server. In the absence of a WAL-based approach, a best-effort deletion in the router is as good as doing it at the server because all the issues you talk about can occur with server restarts and crashes as well.

Also, there are other implementation factors to consider here: the thing about doing things at the server is that the total load on the cluster actually doubles or triples (as each server that does the metadata blob deletion will have to initiate the chunk deletion). But then again you get the benefits of redundancy as well. Additionally, servers may need to make connections to other servers with which they do not have any replicas in common and so on.

The point you make about losing deletes during a restart (which can exist at the server as well in the absence of a WAL) can be solved to an extent by allowing a few seconds after the shutdown is initiated for the router to clean up. This is actually orthogonal and if the router is not already doing it, it should be doing this.

**Comment by nsivabalan** [comment]
I do agree on both sides. A frontend shouldn't need to maintain any states per se. But if I want to back up @vgkholla 's suggestion, that solution isn't clean either. As of now, servers don't interact with any other servers and introducing this will break that abstraction. Also, whether server will directly contact other servers or will use the router is debatable. If we go via directly contacting servers, do we do a do a quorum writes or just one successful write is also up for discussion. So this list goes on to cover all the cases. But on the high level, this looks like server is being loaded with much more functionality than what it is supposed to do. So, inclined towards frontend/router async deletes.
