### ISSUE TITLE
Question about Searching or Custom Ambry IDs

### ISSUE THREAD

**Issue by mtolman** [linkedin/ambry#372]
Hi,
Does Ambry allow you to use custom blob IDs, or does the REST API let you look for a blob that has a specific metadata value? 
I'm thinking about a use case where a client would want to check the server to see if a blob with a particular hash exists before POSTing a blob that is identical to one that is already stored in Ambry.

Thanks,
Mike

**Comment by vgkholla** [comment]
Not sure I completely understand your question but if you have to generate IDs a certain way for your use case, I think you might be able to extend `BlobIdFactory` and `BlobId` and override their functions to generate a blob ID that is a combination of the partition and the hash of the file (instead of UUID).

This might require some changes in `NonBlockingRouter` though. It is tightly coupled to the `BlobId` implementation so I suspect this isn't easy. But it is something you can think about keeping in mind that not everyone will want this kind of support. So whatever we design and implement has to be general enough that it can be replaced easily.

**Comment by vgkholla** [comment]
Closed due to inactivity - Please reopen if required.
