### ISSUE TITLE
Make replication agnostic to changes in log offsets

### ISSUE THREAD

**Issue by vgkholla** [linkedin/ambry#430]
In preparation for implementing compaction, replication (in particular the replication token) has to be able to deal with the changes in the underlying indexes and logs. There are a couple of options to do this

1) Reset to 0 every time there is a change in log offsets/indexes (least desirable)
2) Make replication agnostic to physical offsets - decouple it with the underlying log physical offsets and indexes completely.
3) Don't decouple replication with the logs/indexes but allow the store to detect invalid replication tokens and reconfigure them without losing any ground.

**Comment by vgkholla** [comment]
Will upload a high level design for option 3 soon.

**Comment by vgkholla** [comment]
[Here](https://docs.google.com/document/d/1Lg2Alp5jPfD9NkvDExi0LuLKuurRllV6l3s2-D5YCLg/edit?usp=sharing) is an initial write up of the design. Please comment

**Comment by vgkholla** [comment]
Updated the document to address some important deficiencies pointed out by @pnarayanan

**Comment by vgkholla** [comment]
Document updated based on compaction design.

**Comment by nsivabalan** [comment]
Fix:
Basically, a new Reset Key is introduced in every Index Segment which will be pointing to the first key in the log segment along with its type(Put/Delete) that the index segment refers to.  This reset key will returned as part of the StoreFindToken during replication. If the Offset(name + storeKey) that the storeToken is referring to becomes invalid (due to compaction) during a findEntriesSince() call, the store token is reset to the index segment containing the reset key from the storetoken and entries starting from that offset is returned.

First patch:
Introducing ResetKey in indexSegment 

Second patch:
Add reset key to StoreFindToken returned as part of FindEntriesSince() call. StoreFindToken will have reset key only in read path and not in write path

Third patch:
StoreFindToken writes the reset key during serialization as well. So, a FindEntriesSince() will reset the token based on the reset key if need be

**Comment by cgtz** [comment]
This has been completed
