### ISSUE TITLE
Remove ssl.enabled.datacenters

### ISSUE THREAD

**Issue by vgkholla** [linkedin/ambry#448]
The config `ssl.enabled.datacenters` is redundant with `clustermap.ssl.enabled.datacenters`. Since `clustermap.ssl.enabled.datacenters` is the better abstracted config, the use of `ssl.enabled.datacenters` must be removed. Having both around leaves room for bugs and inconsistencies (for e.g, the one fixed in #437)

`ssl.enabled.datacenters` is used in replication and in related tests (server integration tests for e.g). This usage needs to be changed and the config needs to be removed.

**Comment by pnarayanan** [comment]
Just to clarify - `clustermap.ssl.enabled.datacenters` (in `ClusterMapConfig`) was introduced specifically because `ssl.enabled.datacenters` (in `SslConfig`) is not the right place for the parameter. 
`SSLConfig` contains all the configurations for establishing and communicating over SSL. Whether or not a particular communication should be done over SSL is outside the scope of this config. That belongs in the `ClusterMapConfig`.
The idea was to bring in the new config and phase out the old one which was kind of dependent on phasing out the coordinator (in order to not make any more changes to it). Now that the coordinator is phased out, this is unblocked.
