### ISSUE TITLE
Add pause and resume to HardDeletes 

### ISSUE THREAD

**Issue by nsivabalan** [linkedin/ambry#529]
For compaction, we are in need of this feature, where in, hard deletes should be paused and resumed when required. The BlobStoreCompactor will place these calls when it is about to trigger compaction on the respective store. And when the compaction is complete, it is expected to call hardDelete.resume() to resume hard deletes. 

Requirement have been changed based on feedback and some discussions. so some comments below may not be relevant.

So, here is the expectation from a pause() call in hard deleter.
* Any on-going hard delete cycle should have been completed(flushed, persisted)
* HardDeleteRecovery range should have been pruned(empty) and tokens should have been persisted

Above conditions have to be taken care of before returning from pause().

Once resume() is called, hard delete should continue where it was paused before. During resumption, all tokens (start token, end token and startTokenSafeToPersist) are expected to point to same value and recovery range should be empty. Any new deleted entries (from the time it was paused) will continue to be hard deleted if they are eligible to be.

**Comment by pnarayanan** [comment]
@nsivabalan: This issue helps us be on the same page, so thanks for putting this up. Could you sync up with @vgkholla on the requirements so that we are all indeed on the same page? Specifically, since the overall goal of "pausing" is to ensure that hard deletes are in a consistent state and that a crash would not require a hard delete recovery, how can a caller ensure that the hard delete recovery range is empty? Wouldn't you rather want the `pause()` to return after everything is in a consistent state?

**Comment by vgkholla** [comment]
Was addressed in #521
