### ISSUE TITLE
Adding support for BlobStoreStats in BlobStore

### ISSUE THREAD

**Issue by nsivabalan** [linkedin/ambry#530]
Stats related to BlobStore should be exported via BlobStoreStats to be used by the CompactionManager.

The initial implementation of this class will not have any intelligence and will scan the indexes(on demand) completely when any API calls are made. It may not persist any collected data. Going forward, this will change. We may persist the data, collect stats more "intelligently", actively push data from the BlobStore or do any other multitude of things.

The initial implementation will only contain data for "right now" in the sorted maps.

AC:
1. Simple and extensible interface
2. Implementation
3. Testing

[StoreStats interface](https://gist.github.com/vgkholla/e9cbaf0f2e101c5bec060687a68d81fb)
[BlobStoreStats class](https://gist.github.com/vgkholla/89f05a18b7747d45f267dc5ba453047b)

1. Store will implement StoreStats interface
2. BlobStore will expose an api as below
BlobStoreStats getBlobStoreStats()

Whenever getBlobStoreStats() is called in, BlobStore scans the entire index/log to collect all the required data and return an instance of BlobStoreStats

**Comment by vgkholla** [comment]
@nsivabalan Could you also briefly describe your idea on _how_ this will be implemented.

**Comment by nsivabalan** [comment]
Whenever getBlobStoreStats() is invoked, will walk through the list of index segments to find the valid data size, used capacity and total capacity per log segment. In the end, will update total used capacity and used capacity.

**Comment by vgkholla** [comment]
Updated the [StoreStats](https://gist.github.com/vgkholla/e9cbaf0f2e101c5bec060687a68d81fb) and [BlobStoreStats](https://gist.github.com/vgkholla/e9cbaf0f2e101c5bec060687a68d81fb) gists to reflect recent discussions. Also added a gist for [TimeRange](https://gist.github.com/vgkholla/d3f40ac1dcbc78e073e8446843a7c44d). 

Also recording the discussion on what counts as "valid data" (`tRef` is the reference time that has been provided because the caller wants a view of the data at the time `tRef`)

1. PUT record with no expiry and no corresponding DELETE record.
2. PUT record expiring at time `tExp` but `tRef` < `tExp`.
3. PUT record with a delete at time `tDel` but `tRef` < `tDel`.
4. DELETE record*

(* in the future, a DELETE record whose corresponding PUT record has already been cleaned up will not count towards valid size).
