### ISSUE TITLE
Add documentation about range requests to the wiki

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#556]
Let us update the "Rest API" section and maybe add a separate section under "Design" with details about it.

**Comment by cgtz** [comment]
Added range request api to https://github.com/linkedin/ambry/wiki/Rest-API

I will convert the google doc into a wiki article

**Comment by vgkholla** [comment]
@cgtz Thanks for updating the API ! A few comments/clarifications on the updated API in the range request section

1. Isn't `accept-range:bytes` even for 200 OK responses? Not sure if it is worth mentioning as an interesting response header (I thought the header is the way of saying range requests are accepted). In that vein, could you update the sample responses for GET and HEAD?
2. The sample response for range requests contains both `Transfer-Encoding: chunked` and `Content-Length: 676`. This should not happen in a real response (is a bug if it does). Could you verify? Drop the `Content-length` if necessary since the threshold for `Transfer-Encoding: chunked` is configurable.
3. If specifying the byte range is a standardized way of doing it, you can also provide a link to the standard.
4.

**Comment by cgtz** [comment]
@vgkholla Thanks for the comments!
1. I will remove this header from the documentation and fix the sample responses.
2. Thanks for catching that. Fixed.
3. Sure.
