### ISSUE TITLE
Detect healthy nodes upfront by a server rather than waiting for retry backOff 

### ISSUE THREAD

**Issue by nsivabalan** [linkedin/ambry#558]
Whenever a node is detected to be down, the cluster manager marks the node as down and retry's after retry.backOff.ms. So, this limits our time to detect the an up node (become healthy from unhealthy) to a minimum of retry.backOff.ms. The same is the case for frontend as well as server. 

One possible optimization we could do with servers is with the help of ReplicaMetadataRequest coming in from the node being down, a server(replica) could detect that a node/disk is up even before retry.backOff.ms. This applies only for servers and not possible with frontends as they don't participate in replication.

**Comment by asinghai** [comment]
How does helix+d2 change this picture?

On Mar 8, 2017, at 12:38, Sivabalan Narayanan <notifications@github.com>
wrote:

Whenever a node is detected to be down, the cluster manager marks the node
as down and retry's after retry.backOff.ms. So, this limits our time to
detect the an up node (become healthy from unhealthy) to a minimum of
retry.backOff.ms. The same is the case for frontend as well as server.

One possible optimization we could do with servers is with the help of
ReplicaMetadataRequest coming in from the node being down, a
server(replica) could detect that a node/disk is up even before
retry.backOff.ms. This applies only for servers and not possible with
frontends as they don't participate in replication.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/linkedin/ambry/issues/558>, or mute the thread

**Comment by nsivabalan** [comment]
yes, with helix coming in, guess this may not be required. Will close the issue then.
