### ISSUE TITLE
Introduce a bit in BlobId to indicate simple/data/metadata blob

### ISSUE THREAD

**Issue by vgkholla** [linkedin/ambry#940]
It is useful to know whether a blob is metadata blob in two known (and maybe more) situations
1) Background delete
2) TTL update

Having this information will help avoid an unnecessary GET

**Comment by lightningrob** [comment]
@vgkholla @pnarayanan Is there a use case for distinguishing between simple and data chunk blobs, or would it be sufficient to add a single-bit boolean flag isMetadata?  The former likely entails a higher task effort to modify the router code to set the flag bit(s) properly on BlobId construction.

At the point in PutOperation where BlobId is constructed, it is easy to check if the blob is for metadata.  However, it's not clear how to distinguish between simple and chunked in this part of the flow, and may require refactoring to get it.  The code that sends the notification (with type simple/composite/data) happens after the data requests complete, at which point the BlobId's are already set.

**Comment by pnarayanan** [comment]
@lightningrob you are right that notification has it easy, because it happens after the fact. This is not straightforward, but I think if we are going to embed this information in the id, it is worth adding this information.

I took a quick look and I feel that it may not require a lot of refactoring to distinguish between simple (whole) blob and a data chunk. As you would have seen by now, the `ChunkFiller` thread calls into `fillChunks()` to fill the chunks, and eventually calls into `onFillComplete()` when a chunks is "done", which calls into `prepareForSending()` which in turn creates the `BlobId`. There are 2 possibilities here as far as the first chunk filling is concerned:

1. First chunk filling finishes before MAX_CHUNK_SIZE is reached because there is no more data in the channel (that is, `isChunkFillingDone()` (the EOF condition) becomes true). In this case, the `PutManager` would know right when `onFillComplete()` is called that this is a simple blob.
2. First chunk filling finishes because MAX_CHUNK_SIZE is reached. In this case `PutManager` would not know right then whether this chunk would be a simple blob or just a data chunk. In this case, perhaps what we can do is to not initiate the call to `prepareForSending()` immediately, and instead just keep this first chunk around, until either a) the next byte arrives and we start building the second chunk (at which point we can initiate the `prepareForSending()` for the first chunk with `type == DataChunk`) or b) EOF condition becomes true, in which case we initiate `prepareForSending()` for the first chunk with `type == MetadataChunk`.

**Comment by lightningrob** [comment]
Per discussion, we will implement the BlobDataType as two bits within the BlobId flag, but initially we will populate only two values: Metadata, and DataChunk.  The third value, Simple, cannot be determined trivially during chunk filling (due to the asynchronous nature of the process and callbacks), so we will implement that later.

Thinking out loud, in the case where we know that the first chunk will be the last one (from the fillingComplete flag), we could set the value to Simple.  This will likely happen the majority of the time, since most blobs will not be exactly 4MB in size.  Only in that rare case would the blob be identified incorrectly as DataChunk rather than Simple.
